### ISSUE TITLE
Glitch demo broken

### ISSUE THREAD

**Issue by tmcw** [GoogleChromeLabs/browser-fs-access#103]
<img width="957" alt="CleanShot 2022-04-14 at 12 31 30@2x" src="https://user-images.githubusercontent.com/32314/163433405-02cc1462-6f53-40ed-95d9-51dc92a3c733.png">

Was attempting to debug problems in Firefox, and unfortunately ~~the demo is now broken in Firefox.~~

The demo is broken across all browsers.

**Comment by tmcw** [comment]
I'm trying to get anything working in Firefox, and it really seems like the legacy method is broken there too https://codesandbox.io/s/infallible-shadow-6p01z2?file=/src/index.js

**Comment by tomayac** [comment]
You should import the module. The CJS is meant for bundlers.

**Comment by tomayac** [comment]
It looks like it tried to import the .cjs. For now fixed via passing it the full URL to the .mjs: https://unpkg.com/browser-fs-access@0.27.0/dist/index.mjs.

**Comment by tomayac** [comment]
Fixed properly by re-introducing the `"browser"` field in `package.json`. Please update to `v0.28.0`.

**Comment by tomayac** [comment]
When you now open in the browser or `import` in JavaScript from the URL https://unpkg.com/browser-fs-access, you’re properly redirected to https://unpkg.com/browser-fs-access@0.28.0/dist/index.mjs by the unpkg CDN, which wasn’t the case before.
