### ISSUE TITLE
Crash if you pass a blob without a `.stream()` method to fileSave on fs-access browers

### ISSUE THREAD

**Issue by tmcw** [GoogleChromeLabs/browser-fs-access#105]
Problem line:

https://github.com/GoogleChromeLabs/browser-fs-access/blob/b3be8c6bd93d7be3388aed3ca77da258283494ba/src/fs-access/file-save.mjs#L94

This bug is relatively simple: `blob` isn't defined. This line should probably reference `blobOrResponse`.

**Comment by tomayac** [comment]
Fixed via https://github.com/GoogleChromeLabs/browser-fs-access/commit/9d88346ff973ed773879aebe1807275944154a18.

**Comment by tomayac** [comment]
Just released [v0.28.1](https://github.com/GoogleChromeLabs/browser-fs-access/releases/tag/v0.28.1) that includes this fix.
