### ISSUE TITLE
fs blocked for some users

### ISSUE THREAD

**Issue by dwelle** [GoogleChromeLabs/browser-fs-access#110]
Reported https://github.com/excalidraw/excalidraw/issues/5100 — two different errors, maybe related, maybe not.

Both on Chrome, MacOS Monterey. I currently don't have access to Monterey so can't reproduce.

One of the errors was reproduced on the [demo page](https://googlechromelabs.github.io/browser-fs-access/demo/) as well, so not related to Excalidraw.

**Comment by tomayac** [comment]
Responded in https://github.com/excalidraw/excalidraw/issues/5100. Let's keep the discussion there for now.
