### ISSUE TITLE
can't get handle from directoryOpen function

### ISSUE THREAD

**Issue by sytolk** [GoogleChromeLabs/browser-fs-access#111]
The File System Access API return handle 
```javascript
const dirHandle = await window.showDirectoryPicker();
```
but directoryOpen return files[] in selected directory:
```javascript
const fsAccess = require("browser-fs-access");
  const blobsInDirectory = await fsAccess.directoryOpen({
    recursive: false,
  });
```
How can I get selected directory path only?

**Comment by sytolk** [comment]
Fixed get handle without using [browser-fs-access](https://github.com/GoogleChromeLabs/browser-fs-access)
Public

**Comment by tomayac** [comment]
You can obtain the handles from the returned files, see this [demo](https://spicy-sepia-handle.glitch.me/) and the relevant snippet below:

```js
import { directoryOpen } from "https://unpkg.com/browser-fs-access";

document.querySelector("button").addEventListener("click", async () => {
  const files = await directoryOpen({ recursive: true });
  files.forEach((file) => {
    console.log("FileSystemFileHandle", file.handle);
    console.log("FileSystemDirectoryHandle", file.directoryHandle);
  });
});
```

<img width="669" alt="Screen Shot 2022-05-04 at 10 45 13" src="https://user-images.githubusercontent.com/145676/166649187-f88d58cf-97e6-45c5-9264-9f4693282dbf.png">

This is for the directory structure below:

<img width="179" alt="Screen Shot 2022-05-04 at 10 48 09" src="https://user-images.githubusercontent.com/145676/166649687-29dd1397-4a14-4951-aa7e-17fa9a1e7910.png">
