### ISSUE TITLE
`fileSave` does not respect `extensions`

### ISSUE THREAD

**Issue by rwv** [GoogleChromeLabs/browser-fs-access#113]
Thank you for adding `fileSave` support (https://github.com/rwv/lookscanned.io/pull/8) for lookscanned.io.
However, `fileSave` does not respect `extensions: ['.pdf']` in my setup. Am I doing anything wrong?

Screenshot:
![image](https://user-images.githubusercontent.com/7891383/170827103-d6fccd37-3bbb-4910-a911-f25e2342d471.png)

The meaning of "所有文件" is "All types"

Therefore, when a user change filename, for example, `doc`. Browser will save file to `doc` instead of `doc.pdf`. 

[Code](https://github.com/rwv/lookscanned.io/blob/ba73622580a666327b3dbbd59541d62907c711f5/src/components/ScanSettings/GenerateScannedPDFSetup.ts#L40)
``` javascript
await fileSave(blobPromise, {
  fileName: filename,
  extensions: [".pdf"],
  startIn: "downloads",
  id: "lookscanned",
});
```

Thank you!

**Comment by tomayac** [comment]
Hmm, it does for me on macOS. What operating system are you on? 

<img width="793" alt="Screen Shot 2022-05-30 at 17 16 58" src="https://user-images.githubusercontent.com/145676/171021624-735f5ac9-6d89-46f7-b615-6c1d4283b39a.png">

**Comment by rwv** [comment]
Google Chrome `101.0.4951.67` & Edge `101.0.1210.53` on Windows 11 Version 21H2

**Comment by rwv** [comment]
On macOS it works for me as well. (Chrome `100.0.4896.127` on macOS Version 10.15.6)
<img width="348" alt="Screen Shot 2022-05-30 at 11 25 17 PM" src="https://user-images.githubusercontent.com/7891383/171023113-4a87c8cb-f4b0-457d-885d-5d6e85c609d4.png">

**Comment by tomayac** [comment]
Can you try the demo on https://googlechromelabs.github.io/browser-fs-access/demo/ and click "Save Image File" to see if this saves as a `.png`?

**Comment by rwv** [comment]
> Can you try the demo on https://googlechromelabs.github.io/browser-fs-access/demo/ and click "Save Image File" to see if this saves as a `.png`?

It works!

![image](https://user-images.githubusercontent.com/7891383/171024334-c2805542-8f18-4b56-9495-6959e09f18ae.png)

**Comment by rwv** [comment]
I tried adding `mimeTypes` just now and it works. 

![image](https://user-images.githubusercontent.com/7891383/171025078-9e1c0e68-7b69-4232-8e03-047cdf3c6960.png)

`Adobe Acrobat 文档` means `Adobe Acrobat Document`

**Comment by tomayac** [comment]
Oh, interesting. It's very weird that it would work for `.png` but not for `.pdf`. Thanks for sharing the fix, though.

**Comment by rwv** [comment]
This happens when `mimeTypes` is not set and use `Promise<Blob>`

`Promise<Blob>` causes `type` to be `null`

https://github.com/GoogleChromeLabs/browser-fs-access/blob/617012a85728cb5934c44668652d11b78cfb7256/src/fs-access/file-save.mjs#L34-L45

Therefore, there's no match in the `if` chain causes `types[i].accept == {}`

https://github.com/GoogleChromeLabs/browser-fs-access/blob/617012a85728cb5934c44668652d11b78cfb7256/src/fs-access/file-save.mjs#L46-L61

**Comment by unpervertedkid** [comment]
> Oh, interesting. It's very weird that it would work for `.png` but not for `.pdf`. Thanks for sharing the fix, though.

I think it does not work for `.png`. This from my observation and experiments seems to be a windows issue. Even saving an image in excalidraw does not respect the extensions. You can refer to [#7860](https://github.com/excalidraw/excalidraw/pull/7860) .

**Comment by tomayac** [comment]
> This from my observation and experiments seems to be a windows issue.

That's correct. It's a [known limitation](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/file#unique_file_type_specifiers:~:text=the%20exact%20interface%20differs%20across%20browsers%20and%20operating%20systems) of the fallback API, so it's always recommended to add both, extensions _and_ MIME types.
