### ISSUE TITLE
Chromium on Linux fails to save files

### ISSUE THREAD

**Issue by tmcw** [GoogleChromeLabs/browser-fs-access#118]
So, I'm not an expert on the differences between Chrome and Chromium and any possible native fs difference between Mac, Linux, etc. but I've gotten reports from the field and can replicate locally in a Ubuntu VM that attempting to use browser-fs-access in Chromium on Ubuntu consistently produces `AbortError` failures:

<img width="929" alt="CleanShot 2022-06-28 at 10 28 05@2x" src="https://user-images.githubusercontent.com/32314/176204744-c0ff1659-6229-4c91-9d8d-7f0ba8613a49.png">

This can be replicated on the demo as well as in my application. As far as I can tell, Chromium on Linux advertises support for the native filesystem API and breaks if you try to use it.

**Comment by tmcw** [comment]
Did some digging, seems like it tracks back to these issues: https://bugs.chromium.org/p/chromium/issues/detail?id=1264708#c10

And it looks like the solution is that Chromium/Linux requires the `description` parameter. Tested that and it seems to fix behavior. I think on the browser-fs-access side (assuming that Chromium doesn't fix its behavior), a solution would be either to make the `description` member of the options argument required, or to have a non-empty default value for Description.

**Comment by tomayac** [comment]
Oh, nice. This would be an easy fix. In meeting all of the rest of today, but will definitely look tomorrow.

**Comment by tomayac** [comment]
Confirmed working! 

<img width="981" alt="Screen Shot 2022-06-29 at 13 23 50" src="https://user-images.githubusercontent.com/145676/176425451-b7c3abcf-79d2-4669-9f42-1a069a6c3851.png">
