### ISSUE TITLE
Permission issues on Qutebrowser

### ISSUE THREAD

**Issue by MasseR** [GoogleChromeLabs/browser-fs-access#123]
There are permission issues when trying to download files (images or the `*.excalidraw` file), or when trying to export the link to clipboard. The devtools report that the user has aborted the request, but the user is never presented with any permission requests.

![image](https://user-images.githubusercontent.com/41126/185363695-a15952aa-c523-4d51-8e50-3649e5aea13a.png)

**Comment by tomayac** [comment]
This is a Chrome issue and tracked as https://crbug.com/1264708. Thanks for reporting nontheless.
