### ISSUE TITLE
FileSystemDirectoryHandle does not have proper types

### ISSUE THREAD

**Issue by Johan-Liebert1** [GoogleChromeLabs/browser-fs-access#125]
A lot of properties on `FileSystemDirectoryHandle` are not added to types. 

Defined Types

```
/** Available only in secure contexts. */
interface FileSystemDirectoryHandle extends FileSystemHandle {
    readonly kind: "directory";
    getDirectoryHandle(name: string, options?: FileSystemGetDirectoryOptions): Promise<FileSystemDirectoryHandle>;
    getFileHandle(name: string, options?: FileSystemGetFileOptions): Promise<FileSystemFileHandle>;
    removeEntry(name: string, options?: FileSystemRemoveOptions): Promise<void>;
    resolve(possibleDescendant: FileSystemHandle): Promise<string[] | null>;
}

declare var FileSystemDirectoryHandle: {
    prototype: FileSystemDirectoryHandle;
    new(): FileSystemDirectoryHandle;
};
```

Not included in types

![image](https://user-images.githubusercontent.com/39958783/191083414-6cfc0b49-d20a-4940-8527-ebffaa69a764.png)

**Comment by tomayac** [comment]
This library doesn't define types for `FileSystemDirectoryHandle`, as you can see in [`index.d.ts`](https://github.com/GoogleChromeLabs/browser-fs-access/blob/main/index.d.ts). It uses whatever TypeScript already ships with. Maybe updating to the latest version fixes this for you.
