### ISSUE TITLE
Use showPicker() instead of click() "legacy"

### ISSUE THREAD

**Issue by jesben** [GoogleChromeLabs/browser-fs-access#126]
My iOS users report sometimes that file browse do not show. Super strange, I don't think there's anything wrong with the code, it's probably more an iOS bug. But maybe you can count more on showPicker() instead of click(), I don't know... In iOS 16 it is supported.

```
if ('showPicker' in HTMLInputElement.prototype) {
  input.showPicker();
} else {
  input.click();
}
```

Ref:
https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/showPicker

**Comment by tomayac** [comment]
Thanks for the proposal. Let's hope this increases the reliability on iOS.

**Comment by jesben** [comment]
It's me who thanks :)

**Comment by tomayac** [comment]
Now publishes as `v0.31.1`.

**Comment by jesben** [comment]
Perfect I will deploy it this weekend. Will return with status after some time. Thanks.
