### ISSUE TITLE
Error:  Cannot find name 'FileSystemDirectoryEntry'

### ISSUE THREAD

**Issue by narasing494599** [GoogleChromeLabs/browser-fs-access#140]
I installed the package in my angular application and when i am trying to build i get error
`Cannot find name 'FileSystemDirectoryEntry'`
<img width="838" alt="image" src="https://user-images.githubusercontent.com/16819376/223693243-7cb31767-7252-47ab-9402-9570b85a355f.png">

**Comment by tomayac** [comment]
This is actually a TypeScript issue. People have apparently solved it for Angular by following the steps outlined in this [StackOverflow question](https://stackoverflow.com/questions/43693819/filesystem-in-typescript).
