### ISSUE TITLE
Remove Listener Issue

### ISSUE THREAD

**Issue by renato-mauro** [GoogleChromeLabs/browser-fs-access#142]
Hello! Thanks for your work. Helped me a lot. There is a small issue when you are removing the event listener for window focus. As it was registered with useCapture = true, it should be unregistered using also useCapture = true argument.

https://github.com/GoogleChromeLabs/browser-fs-access/blame/5d8a551af106121d010c1c50ca4a15d3cb0b189d/src/legacy/file-open.mjs#LL32

**Comment by tomayac** [comment]
Thank you! Just released `v0.34.0` that includes this fix.

**Comment by hshafie** [comment]
I'm sorry but I don't understand this change.
In v0.34.0, legacy/file-open.mjs, I see:

```
    input.addEventListener('click', () => {
      window.addEventListener('focus', cancelDetector);
    });
```
No useCapture=true 3 argument there and useCapture defaults to false.

**Comment by tomayac** [comment]
You're right. I didn't realize that the link went to outdated code. Sorry.

**Comment by hshafie** [comment]
No problem. Thank you for the quick response and of course, for your very useful library.
