### ISSUE TITLE
Network folders

### ISSUE THREAD

**Issue by tomasgrunt** [GoogleChromeLabs/browser-fs-access#149]
Hi,

this is not an issue but I would like to know, if this browser-fs-access can be used for:

- access to local shared folder on server, so I can specify which folder will it be as parameter
- upload one or more images from mobile device to that folder

Thank you

**Comment by tomayac** [comment]
Just did a [quick experiment](https://stackblitz.com/edit/vitejs-vite-pcn5gi?file=main.js,index.html&terminal=dev). You need to pass a `FileSystemHandle` as the `startIn` option, and it does work if this points to a network location. I have split it up in two buttons so you can see the effect more easily. 

```js
import { fileOpen } from 'browser-fs-access';

let handle;

document.querySelector('.button1').addEventListener('click', async () => {
  try {
    const file = await fileOpen();
    handle = file.handle;
  } catch (err) {
    console.log(err)
  }
});

document.querySelector('.button2').addEventListener('click', async () => {
  try {
    const file = await fileOpen({    
      startIn: handle
    });  
  } catch (err) {
    console.log(err)
  }
});
```

1. Open a file from a network drive to get a handle with the first button:
   ![Screenshot 2023-11-29 at 11 26 20](https://github.com/GoogleChromeLabs/browser-fs-access/assets/145676/b2d8c952-2dd1-471b-8cda-c6b337819667)
1. The second button then starts the dialog in the network drive:
   ![Screenshot 2023-11-29 at 11 26 33](https://github.com/GoogleChromeLabs/browser-fs-access/assets/145676/5b9a4e8f-a2c0-44ab-8d2a-d1e7378d5cd7)
