### ISSUE TITLE
How to serialize file handles?

### ISSUE THREAD

**Issue by GreenFootballs** [GoogleChromeLabs/browser-fs-access#30]
The [article at web.dev](https://web.dev/file-system-access/) mentions that file handles are serializable, and can be stored in IndexedDB (and presumably chrome.storage?), but there's no example and I haven't been able to make this work. What is the procedure for serializing the file handles for storage?

**Comment by tomayac** [comment]
I have just documented the [answer on StackOverflow](https://stackoverflow.com/a/65938910/6255000).
