### ISSUE TITLE
'self is not defined' in Nuxt SSG

### ISSUE THREAD

**Issue by kota-yata** [GoogleChromeLabs/browser-fs-access#34]
Since Nuxt Universal(SSR/SSG) create page on server side, openFile function failed in Nuxt project
```
Reference Error : self is not defined
```

To deal with this error, I added a conditional branch in supported.mjs of in node_modules and it works well.

```
// @license © 2020 Google LLC. Licensed under the Apache License, Version 2.0.
let e;
if(process.browser) {
  e="chooseFileSystemEntries"in self?"chooseFileSystemEntries":"showOpenFilePicker"in self&&"showOpenFilePicker";
}

export default e;

```

I'm going to send PR soon

**Comment by tomayac** [comment]
See https://github.com/GoogleChromeLabs/browser-fs-access/pull/35#issuecomment-787809762 for the rationale for closing this.
