### ISSUE TITLE
Docblocks swapped for fileSave

### ISSUE THREAD

**Issue by Stefaans** [GoogleChromeLabs/browser-fs-access#44]
The docblocks are swapped around for the File System Access API and legacy instances of the fileSave functions:
- fs-access/file-save.mjs says "Saves file to disk using the (**legacy**) File System Access API."
- fs-access-**legacy**/file-save.mjs says "Saves file to disk using the File System Access API."

Thanks for a very useful package!

**Comment by tomayac** [comment]
`<3` Thank you! Just released v0.16.1, which contains a fix (and a couple more fixes I noticed while systematically going through the docs).
