### ISSUE TITLE
Legacy `fileOpen` should resolve with array when `multiple: true`

### ISSUE THREAD

**Issue by dwelle** [GoogleChromeLabs/browser-fs-access#46]
Right now it resolves with `FileList` which is missing some prototype methods so will throw e.g. on `map()`.

**Comment by dwelle** [comment]
Thanks! You beat me to the PR :heart:

**Comment by tomayac** [comment]
This one was [easy](https://github.com/GoogleChromeLabs/browser-fs-access/commit/6269b4a642f810fd4c371f6eb3657a8006d9c197#) :-)
