### ISSUE TITLE
filename not populated in save dialog using Chrome

### ISSUE THREAD

**Issue by ktedore** [GoogleChromeLabs/browser-fs-access#49]
example `https://browser-fs-access.glitch.me/`

Tested in
Windows Chrome  Version 90.0.4430.212 (Official Build) (64-bit)
MacOS Chrome Version 90.0.4430.212 (Official Build) (x86_64)

**Comment by tomayac** [comment]
That’s a feature that’s supported as of Chrome 91, see [this blog post](https://blog.chromium.org/2021/04/chrome-91-handwriting-recognition-webxr.html).
