### ISSUE TITLE
Return the directory handle after a directoryOpen

### ISSUE THREAD

**Issue by Amatewasu** [GoogleChromeLabs/browser-fs-access#51]
Hi,

It would be great to allow us to retrieve the directory handle after a `directoryOpen` like what is done with `fileOpen`. Thus, we could save a file in that directory.

Have a great day!

**Comment by tomayac** [comment]
Thanks for the suggestion. Just released v0.17.2 that includes this. Look for a `directoryHandle` property on the files returned by `directoryOpen()`.

**Comment by Amatewasu** [comment]
Great! Thanks a lot!

**Comment by Senne** [comment]
How would you actually use the directory handle in this case? The parameter `existingHandle` in `fileSave` only accepts a file handle, so I'm still confused on how to save a file directly to a directory…

**Comment by tomayac** [comment]
You can absolutely do this today. Go to https://vscode.dev/, open a local folder, then create a new file or folder and the app will ask you if you want to grant write access to the local folder and then go on and create the new file or folder.

**Comment by tomayac** [comment]
Check out this [article section](https://web.dev/file-system-access/#creating-or-accessing-files-and-folders-in-a-directory) on how to do this. Note that this is of course no longer polyfillable with browser-fs-access.

**Comment by Senne** [comment]
Oh perfect, that's exactly what I was looking for. Thanks so much!
