### ISSUE TITLE
SSR support

### ISSUE THREAD

**Issue by pelikhan** [GoogleChromeLabs/browser-fs-access#54]
When using this library with a server-side-rendering module, it fails to load in webpack because of references to "self".

**Comment by pelikhan** [comment]
```
ReferenceError: self is not defined
    at .....\browser-fs-access\dist\supported.mjs:2:15
```

**Comment by tomayac** [comment]
I have asked for help from some bundler experts internally at Google and hope to get back with an answer. Thanks for your patience.

**Comment by pelikhan** [comment]
Gating with typeof self !== “undefined” should do it. Same for window.
________________________________

**Comment by tomayac** [comment]
Oh, I see, if this would work for you, then it's an easy fix.

**Comment by pelikhan** [comment]
Untested but this is how one guards against any global object that is not available outside the browser.
________________________________

**Comment by tomayac** [comment]
See https://github.com/GoogleChromeLabs/browser-fs-access/commit/78e2d3f459486bb2bac51e20303c0e820393b921#diff-a5502953df7ea5447a2e73f2d7ae3829caf96df2a697095eac6f30b9e636148d for the fix. Hope this works.
