### ISSUE TITLE
Unexpected token in legacy file-open and directory-open

### ISSUE THREAD

**Issue by haexhub** [GoogleChromeLabs/browser-fs-access#58]
Hi,

I'm using browser-fs-access with nuxt and got an error about unexpected tokens in legacy/file-open.mjs and legacy-directory-open.mjs.

`
export default async(
  e={})=>new Promise(((t,n)=>{const i=document.createElement("input");i.type="file";const s=[...e.mimeTypes?e.mimeTypes:[],e.extensions?e.extensions:[]].join();let c;i.multiple=e.multiple||!1,i.accept=s||"";const l=()=>c(n);e.setupLegacyCleanupAndRejection&&(c=e.setupLegacyCleanupAndRejection(l)),
i.addEventListener("change",(()=>{c?.(),t(i.multiple?Array.from(i.files):i.files[0])})),i.click()}));
`

The problem is the ? Operator 

`c?.(),t(i.multiple?Array.from(i.files):i.files[0])})),i.click() // doesn't work` 
`c(),t(i.multiple?Array.from(i.files):i.files[0])})),i.click() // works` 

I'm not sure why webpack is complaining about, because it's valid javascript.

**Comment by tomayac** [comment]
Thanks for the report. Just released `v0.19.2` that fixes this.

**Comment by haexhub** [comment]
Wow. What an amazing response time! :1st_place_medal: 
Thank you very much!
Could you please explain me the problem a bit bit more?
Why is the optional chaining not working here?

**Comment by tomayac** [comment]
Probably in your webpack config you target browsers that don't match the [compatibility](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining#browser_compatibility) of the feature.
