### ISSUE TITLE
Safari Support Issues/limitations question ...

### ISSUE THREAD

**Issue by fabiogomessilva** [GoogleChromeLabs/browser-fs-access#59]
On Safari the fileOpen API works fine (the Upload file dialog show up), but when using the fileSave API the ​"Save As..." dialog only shows up when changing browser preferences

Is there any way to always shows up the "Save As...." dialog on Safari browser independent of browser preferences? Today we have to set "Preferences/General/File Download location" to "Ask for each download".

My current Safari version is 14.1.1

**Comment by tomayac** [comment]
I have set my iPhone (on iOS 15) to always download to my iCloud Downloads folder, without asking, and the download works fine. There is no longer a way to save to a user-determined folder individually for each download it seems.
