### ISSUE TITLE
List of accepted file types

### ISSUE THREAD

**Issue by PeterNjeim** [GoogleChromeLabs/browser-fs-access#60]
Is it possible to allow multiple file types, separated in a list, with separate descriptions for each?

Of course, I can allow as many file types as I want, however I would like to follow what desktop programs do, and separate them out like this:
![image](https://user-images.githubusercontent.com/26418974/128024926-3102b33b-4675-4628-9e76-77d2b54cc051.png)
Not a deal breaker obviously, just wondering if it's even possible on the web

**Comment by tomayac** [comment]
This is certainly possible with the File System Access API:

```js
await showOpenFilePicker({
  types: [
    {
      description: 'Text Files',
      accept: {
        'text/plain': ['.txt', '.text'],
        'text/html': ['.html', '.htm']
      }
    },
    {
      description: 'Images',
      accept: {
        'image/*': ['.png', '.gif', '.jpeg', '.jpg']
      }
    }
  ],
});
```

I'm looking to add a way to make this happen in `browser-fs-access`.

**Comment by tomayac** [comment]
This is now supported as of `v0.20.0`, which will go out in a moment.

<img width="789" alt="Screen Shot 2021-08-06 at 17 37 37" src="https://user-images.githubusercontent.com/145676/128535809-715768be-389d-4c87-96db-007b6678ad05.png">
