### ISSUE TITLE
Need to update types

### ISSUE THREAD

**Issue by tomayac** [GoogleChromeLabs/browser-fs-access#61]
`fileOpen()` and `fileSave()` now either take an options object, or an array of options objects. The [types](https://github.com/GoogleChromeLabs/browser-fs-access/blob/main/index.d.ts) need to reflect this new change.

```js
// New as of v0.20.0
fileOpen([
    {
      description: 'Image files',
      mimeTypes: ['image/jpg', 'image/png', 'image/gif', 'image/webp'],
      extensions: ['.jpg', '.jpeg', '.png', '.gif', '.webp'],
      multiple: true,
    },
    {
      description: 'Text files',
      mimeTypes: ['text/*'],
      extensions: ['.txt'],
    },
]);
```

or 

```js
// Previous behavior
fileOpen({
  description: 'Image files',
  mimeTypes: ['image/jpg', 'image/png', 'image/gif', 'image/webp'],
  extensions: ['.jpg', '.jpeg', '.png', '.gif', '.webp'],
  multiple: true,
});
```

**Comment by tomayac** [comment]
People who have touched the types file before: @dwelle @jmrog @nanaian @raid @fvilers. Anyone able to help? I'm personally not familiar enough with TypeScript.

**Comment by jmrog** [comment]
Sure, I can take a look!

**Comment by fvilers** [comment]
I'd write something like this:
```
type FileOpenOptions = {
...
}

fileOpen(FileOpenOptions | FileOpenOptions[]): FileOpenReturnType;

```

**Comment by jmrog** [comment]
> I'd write something like this:
> 
> ```
> type FileOpenOptions = {
> ...
> }
> 
> fileOpen(FileOpenOptions | FileOpenOptions[]): FileOpenReturnType;
> ```

I did roughly this in my commit above. Your review would be appreciated! 😄

**Comment by jmrog** [comment]
Caught a small but in that PR, let me update real quick.

**Comment by jmrog** [comment]
> Caught a small but in that PR, let me update real quick.

Updated now.

**Comment by jmrog** [comment]
@tomayac Everything in the PR as-is works, but I'm curious about something. Is it the case that, for `fileOpen`, only the _first_ object in the `options` array (when it is an array rather than a scalar value) can have a `multiple` property? Looking at [the code](https://github.com/GoogleChromeLabs/browser-fs-access/blob/main/src/fs-access/file-open.mjs#L50), that at least seems to be the case (`multiple` properties on other options objects are ignored). The PR doesn't currently enforce that, though perhaps it could be made to do so (I'm not immediately sure).

**Comment by tomayac** [comment]
Yeah, it’s a bit ugly, but this way there’s compatibility with the existing API.

**Comment by jmrog** [comment]
I noted this on the thread for the PR itself, but I'll note it here too: I updated the PR to also enforce specifying certain properties _only_ on the first options object in the array of options (when an array is provided). As I say there, it makes for a nice developer experience (nice autocomplete and diagnostics), but I'm not sure what TypeScript features you want to use (or, put differently, which TypeScript versions you want to support) in the types for this repo.
