### ISSUE TITLE
Extension contains invalid characters

### ISSUE THREAD

**Issue by PeterNjeim** [GoogleChromeLabs/browser-fs-access#63]
`TypeError: Failed to execute 'showOpenFilePicker' on 'Window': Extension '.mscz,' contains invalid characters.` is the error I'm receiving. Obviously this has to do with how there's a comma at the end of the file extension, which is a real thing. You should consider allowing special characters in file extensions.

![image](https://user-images.githubusercontent.com/26418974/128647357-9ac852cb-54c0-479d-87f9-f2094245e5ac.png)
![image](https://user-images.githubusercontent.com/26418974/128647347-92c4ed72-4c0a-45ba-aaf5-b8b6239f9bdf.png)

**Comment by tomayac** [comment]
I just tried this on macOS (Chrome) and Windows (Edge). In both cases saving and opening `.mscz,` files worked. Could you please let me know the exact operating system and browser version you are using?

**Comment by PeterNjeim** [comment]
I'm using Windows 11 (21H2) build 22000.120 and Edge version 92.0.902.67

**Comment by tomayac** [comment]
I have traced this down to https://crbug.com/1238259. Please star that bug for progress updates. By the way, investigating this issue caused me to find a bug in `v0.20.2`, please update to the latest version `v0.20.3`.

**Comment by PeterNjeim** [comment]
With the release of MuseScore 4, the backup files have been renamed from `.mscz,` to `.mscz~`. Don't know if `~` is supported or not, but this issue might not need fixing if it is supported
