### ISSUE TITLE
Unable to complete previous operation due to low memory

### ISSUE THREAD

**Issue by sh-a-v** [GoogleChromeLabs/browser-fs-access#64]
This happens periodically after opening the file explorer (and selecting a file of any size, even small (~10KB)) or camera.
Trace is not recorded due to browser restart.

_Application version:_
Chrome 92.0.4515.131

_Operating system:_
Android 9

<img src="https://user-images.githubusercontent.com/7159528/129201057-ca92c280-1c52-415d-bb52-fe8ef0c4c0c2.png" width="250">

_Phone memory:_

<img src="https://user-images.githubusercontent.com/7159528/129201724-96321c3e-45da-406f-a11d-9c49dae70153.png" width="250">
<img src="https://user-images.githubusercontent.com/7159528/129201732-20eb6e9a-1ac1-474b-ae89-df3c47ab0a85.png" width="250">

**Comment by tomayac** [comment]
This is https://crbug.com/417742. To fix this, go to your Android device's settings, find the developer options, and turn off "Don't keep activities".

**Comment by sh-a-v** [comment]
> 
> 
> This is https://crbug.com/417742. To fix this, go to your Android device's settings, find the developer options, and turn off "Don't keep activities".

"Permission denied."

Will this bug be fixed by Chrome?
It's difficult to explain to users where and what should be disabled.

**Comment by tomayac** [comment]
Oh, sorry about the permission denial. These are the essential bits:

- [The reporter reported essentially your bug from a file picker in the Gmail app's attachment flow.]
- _Do you have "Don't keep activities" checked in developer settings?_
- _Yes I have checked "don't keep activities" in developer settings_
- _With that setting selected, going to choose a file to download causes chrome to be killed.
   I don't believe that was ever supported, so I'm removing the regression flag.  This is also a rather large undertaking for something that is purely a development option, so I'm not going to mark this as a milestone requirement.  This is a bug that I'm fine with existing forever and I don't think the engineering resources necessary to fix this justify the gain (at least right now)._

**Comment by sh-a-v** [comment]
>     Do you have "Don't keep activities" checked in developer settings?
>     Yes I have checked "don't keep activities" in developer settings

In my case _"Don't keep activities"_ is unchecked and I still get this error a lot anyway.

**Comment by tomayac** [comment]
I have asked for the bug to be made public and commented on you seeing this despite the toggle set to off.
<img width="983" alt="Screen Shot 2021-08-12 at 17 14 46" src="https://user-images.githubusercontent.com/145676/129222332-5f00bcc5-4e59-4465-bf11-2f4d0f4d23c8.png">

**Comment by sh-a-v** [comment]
I disabled "Battery optimization" for Chrome (enabled by default) and it seems it helped.

**Comment by tomayac** [comment]
Thanks for sharing the solution. I have also updated the Chrome bug accordingly.

**Comment by tomayac** [comment]
(By the way, the Chrome bug is now publicly visible.)
