### ISSUE TITLE
Is there a way to get just the path of the selected folder?

### ISSUE THREAD

**Issue by delebash** [GoogleChromeLabs/browser-fs-access#69]
I am trying to get a string path from the selected directory using showDirectoryPicker(),  I do not want to upload anything I just need the selected path.

Does broswer-fs-access have this  feature?
Or do you know how to get selected path from  ` const dirHandle = await window.showDirectoryPicker()`  I am able to get the dirHandle but I cannot find a method or property that gives me the selected directory path.

TY

**Comment by tomayac** [comment]
This is not possible on purpose, please see https://github.com/WICG/file-system-access/issues/282 for the details.
