### ISSUE TITLE
Ability to abort a `directoryOpen`

### ISSUE THREAD

**Issue by Amatewasu** [GoogleChromeLabs/browser-fs-access#75]
When calling the function `directoryOpen({ recursive: true })` and the user selects a large folder (such as C:\ for Windows users for example), it will try to load too many files and the promise will not resolve.

It would be great to add the ability to abort.
I don't know what could be exactly the best parameters to add, but I can think of:
- maxFiles: natural int (after maxFiles found, either the promise resolves prematurely or rejects (second option is best imo))
- timeout: natural int (after timeout ms, the promise is rejected?)
- check (a callback that is called with some information about the folder, such as its name, and then if the callback returns a falsy value, the promise is rejected before opening the recursive folders?)

**Comment by tomayac** [comment]
> * it does not resolve/reject the `directoryOpen` promise that still runs in the background, it could be quite resource-intensive if the user selected a large folder

You could maybe make this work by leveraging the [`legacySetup` parameter](https://github.com/GoogleChromeLabs/browser-fs-access/blob/f7e9753449569c3226ff8caae45a6b4cd5c03ca5/index.d.ts#L164-L196).

> * it includes the elapsed time for the user to select the folder, thereby `Promise.race` will resolve/reject after the sleep duration if the user takes a while to select the folder

That's true. I don't think there is a workaround unfortunately.
