### ISSUE TITLE
Restoring a FileHandle

### ISSUE THREAD

**Issue by steveruizok** [GoogleChromeLabs/browser-fs-access#81]
Hi, I'm trying to restore a `FileHandle` after refreshing a page where a handle had been previously set. I am able to save and load the handle from indexdb as described in this [StackOverflow question](https://stackoverflow.com/questions/65928613/file-system-access-api-is-it-possible-to-store-the-filehandle-of-a-saved-or-loa/65938910#65938910), however the `fileSave` method does not appear to accept it.

Here's the chain of events.

1. Save file
2. Choose name and destination via native window
3. Confirm (and persist file handle in state and in idb)
3. Make changes to file
4. Save file again
5. Changes save in background 
6. Reload window (and restore file handle to state)
7. Save file
8. Back to step number 2 

I would expect number 8 to go to step number 5, rather than step number 2.

I've checked also on Excalidraw, the same behaviour appears to be happening there.

**Comment by tomayac** [comment]
You might be missing the permissions step. Here's a working code sample of one of my apps:

```js
const checkPermissions = async (handle) => {
  const options = { mode: 'read' };
  if ((await handle.queryPermission(options)) === 'granted') {
    return true;
  }
  if ((await handle.requestPermission(options)) === 'granted') {
    return true;
  }
  return false;
};


// …snip…
  try {
    // Start where the user left off.
    // (This uses https://github.com/jakearchibald/idb-keyval 
    // for convenience.)
    const handle = await get(FILE_HANDLE);
    if (handle && (await checkPermissions(handle))) {
      const file = await handle.getFile();
      // …snip…
    }
  } catch (err) {
    console.error(err.name, err.message);
    await del(FILE_HANDLE);
  }
// …snip…
```

Does this work for you?

**Comment by steveruizok** [comment]
Works! Though strangely if I set the mode to `readwrite` the permissions pop-up comes up twice.

**Comment by tomayac** [comment]
Great to hear! This may be a temporary thing, the final permission flow may still change. Closing the Issue then.
