### ISSUE TITLE
Possible incorrect typing

### ISSUE THREAD

**Issue by rodemananthony** [GoogleChromeLabs/browser-fs-access#91]
https://github.com/GoogleChromeLabs/browser-fs-access/blob/d65a322c19cdd8395e3a4a50574dd27752ba5e9a/index.d.ts#L166

While I could be entirely wrong, I believe the type at this line should be `FileSystemDirectoryHandle` instead of `FileSystemDirectoryEntry`.

**Comment by tomayac** [comment]
Good spot. Thank you!
