### ISSUE TITLE
Possibly missing types for FileSystemDirectoryHandle, FileSystemFileHandle

### ISSUE THREAD

**Issue by theo-staizen** [GoogleChromeLabs/browser-fs-access#93]
During compilation typescript complains about missing types for `FileSystemDirectoryHandle` and `FileSystemFileHandle` and as far as I can tell this is correct, as there is only a reference to those types in `index.d.ts`, but no declaration.

![image](https://user-images.githubusercontent.com/66014157/156330076-5a761026-5de0-4936-aaf7-dd6cc1748e20.png)

For a very crude fix, I added the following, as I was only using `fileOpen`

```ts
 declare global {
  interface FileSystemDirectoryHandle extends FileSystemHandle {}
  interface FileSystemFileHandle extends FileSystemHandle {
    createWritable(): Promise<FileSystemWritableStream>
    getFile(): Promise<File>
  }
  interface FileSystemWritableStream extends WritableStream {}
}

```

**Comment by theo-staizen** [comment]
Thanks, that worked, but i had to manually reference it `/// <reference types="wicg-file-system-access" />`
I hope this is only temporary, given that this package is exporting its own types, things should "just work"

**Comment by tomayac** [comment]
I was under the impression TypeScript shipped with an ever-growing set of types, and sometimes updating the TypeScript version resolved issues like this. That being said, I'm not a TS user myself, so may well be wrong.
