### ISSUE TITLE
Published types are incomplete

### ISSUE THREAD

**Issue by goto-bus-stop** [GoogleChromeLabs/browser-fs-access#97]
Only this typings file is included in the published package: https://unpkg.com/browse/browser-fs-access@0.25.3/dist/index.d.ts
The typings files for the things it imports are not there. Maybe this happened after the switch to microbundle?

**Comment by tomayac** [comment]
Thanks for the report. Just fixed this in https://github.com/GoogleChromeLabs/browser-fs-access/commit/0ef17b5eec506448d4e47d65c5c21a94ae7ce53d. 

https://unpkg.com/browse/browser-fs-access@0.26.0/

**Comment by goto-bus-stop** [comment]
Thank you! 😊
